### PR TITLE
[ADD]add route config for dubbo method

### PR DESCRIPTION
**Pull request by scaat**
Use the method field in http to represent the calling method in dubbo.

### CODE REVIEW

**Comment by zhaohuabing** [comment]
@scaat Thanks for your contribution! I have sent out an invitation to you so you can get access to the github secret that stores the dockerhub credential. 

Please accept the invitation and trigger the e2e test again.

**Comment by scaat** [comment]
@zhaohuabing I have triggered the e2e test again, but the error is still reported.

**Comment by zhaohuabing** [comment]
> @zhaohuabing I have triggered the e2e test again, but the error is still reported.

Looks like a restriction of Github. I have modified the workflow, hopefully, it was fixed. Could you please rebase and push again?

**Comment by zhaohuabing** [comment]
> @zhaohuabing I have triggered the e2e test again, but the error is still reported.

Looks like a restriction of Github. I have modified the workflow, hopefully, it was fixed. Could you please rebase and push again?

**Review by zhaohuabing — APPROVED** [review]
LGTM

**Pull request merged**
